#sql = "select a.ourbanklocations as '银行',a.ourbankareaname as '地区' from t_se_payments a where a.ourbanklocations = %s"

sql1 = "select a.tenantid from TSYS_TENANT a where a.tenant_code='TestTenant' "

sql3 = "select * from tsys_package a where a.description='自动化测试套餐' "

sql4 = "delete from tsys_package a where a.description='自动化测试套餐' "

sql5 = "select * from t_sy_directbanks b where b.tenantid='10001' and b.bankid ='102' "

sql6_mys = "INSERT INTO `t_sy_directbanks`(`urid`, `tenantid`, `bankid`, `createdby`, `createdon`, `lastmodifiedby`, `lastmodifiedon`, `rowversion`) VALUES ('18b8429ffd204568a4427cb24edb9998', 10001, '102', 'Felix', '2021-03-10 20:01:33', 'Felix', '2021-03-10 20:01:33', 1) "

sql6_ora = "insert into t_sy_directbanks (URID, TENANTID, BANKID, CREATEDBY, CREATEDON, LASTMODIFIEDBY, LASTMODIFIEDON, ROWVERSION) values ('697d0c081bb64f88ada92f447899adf5', 10001, '102', 'zh', to_date('26-02-2021 09:28:40', 'dd-mm-yyyy hh24:mi:ss'), 'zh', to_date('26-02-2021 09:28:40', 'dd-mm-yyyy hh24:mi:ss'), 1)"

sql7 = "select * from t_sy_directbanks b where b.tenantid='10001' and b.bankid ='505' "

sql8 = "delete from t_sy_directbanks b where b.tenantid='10001' and b.bankid ='505' "

sql9=[
    "delete from tsys_org_user t where t.user_id='Tao' and t.tenantid=10001",
    "delete from tsys_org_user t where t.role_code='TestRole' and t.tenantid=10001",
    "delete from tsys_role_user t where t.role_code='TestRole' and t.tenantid=10001",
    "delete from tsys_role t where t.role_code='TestRole' and t.tenantid=10001"]

sql10=[
    "delete from tsys_user a where a.user_id='Tao' and a.tenantid=10001",
    "delete from tsys_user_ext a where a.user_id='Tao' and a.tenantid=10001",
    "delete from tsys_user_login a where a.user_id='Tao' and a.tenantid=10001"]

sql11=[
    "delete from tsys_org_user t where t.org_id=(select o.org_id from tsys_organization o where o.org_code='TestOrgSet' and o.tenantid=10001)",
    "delete from tsys_organization t where t.org_code='TestOrgSet' and t.tenantid=10001",
    "delete from t_bd_categories t where t.classification = '16' and  t.code='TestOrgType' and t.tenantid=10001",
    "delete from t_bd_categories t WHERE t.code='TestOrgClass' and t.classification='27' and t.tenantid=10001"
    ]

sql2 = [
	"delete from TSYS_ROLE_USER a where a.tenantid= %s ",
    "delete from JBPM4_EXT_PT_TRAN a where a.tenantid= %s ",
    "delete from JBPM4_EXT_PROC_EDITOR a where a.tenantid= %s ",
    "delete from JBPM4_EXT_PRO a where a.tenantid= %s ",
    "delete from T_BD_PARAMVAL a where a.tenantid= %s ",
    "delete from TSYS_USER a where a.tenantid= %s ",
    "delete from T_BA_BANKBALANCES a where a.tenantid= %s ",
    "delete from T_SE_JOURNALBALANCES a where a.tenantid= %s ",
    "delete from T_BI_CHEQUES a where a.tenantid= %s ",
    "delete from T_BI_CHEQUEBOOKS a where a.tenantid= %s ",
    "delete from T_BI_RECDRAFTS a where a.tenantid= %s ",
    "delete from T_BI_RECDRAFTOPERATIONS a where a.tenantid= %s ",
    "delete from T_BI_PAYDRAFTS a where a.tenantid= %s ",
    "delete from T_SE_COUNTERPARTIES a where a.tenantid= %s ",
    "delete from T_BI_RECDRAFTOPERATIONS a where a.tenantid= %s ",
    "delete from t_fl_margininterestdetails a where a.tenantid= %s ",
    "delete from t_fl_margininterests a where a.tenantid= %s ",
    "delete from t_fl_marginoperation a where a.tenantid= %s ",
    "delete from t_fl_margin a where a.tenantid= %s ",
    "delete from t_se_paymentexchangeext a where a.tenantid= %s ",
    "delete from t_se_payments a where a.tenantid= %s ",
    "delete from t_fi_bankfininterestdetails a where a.tenantid= %s ",
    "delete from t_fi_bankfininterests a where a.tenantid= %s ",
    "delete from t_fi_bankfinancialproductops a where a.tenantid= %s ",
    "delete from t_fi_bankfinancialproducts a where a.tenantid= %s ",
    "delete from t_se_recmentdetail a where a.tenantid= %s ",
    "delete from t_se_recments a where a.tenantid= %s ",
    "delete from t_ba_banktransactions a where a.tenantid= %s ",
    "delete from T_BI_RECDRAFTOPERATIONS a where a.tenantid= %s ",
    "delete from T_SE_JOURNALS a where a.tenantid= %s ",
    "delete from T_SE_JOURNALBALANCES a where a.accountid in (select a.urid from T_BA_ACCOUNTS a where a.tenantid= %s )",
    "delete from T_SE_JOURNALS a where a.accountid in (select a.urid from T_BA_ACCOUNTS a where a.tenantid= %s )",
    "delete from T_SE_DISTRIBUTION a where a.tenantid= %s ",
    "delete from T_BA_BANKFREEZETRANS a where a.tenantid= %s ",
    "delete from T_BI_RECDRAFTOPERATIONS a where a.bankaccountid in (select a.urid from T_BA_ACCOUNTS a where a.tenantid= %s )",
    "delete from T_BA_ACCOUNTS a where a.tenantid= %s ",
    "delete from t_if_agreements a where a.tenantid= %s ",
    "delete from t_if_lendingrepays a where a.tenantid= %s ",
    "delete from t_if_lendinglends a where a.tenantid= %s ",
    "delete from t_if_lendings a where a.tenantid= %s ",
    "delete from t_if_loanlends a where a.tenantid= %s ",
    "delete from t_if_loanrepays a where a.tenantid= %s ",
    "delete from t_if_loans a where a.tenantid= %s ",
    "delete from t_bd_uniquecodes a where a.tenantid= %s ",
    "delete from t_if_loansapply a where a.tenantid= %s ",
    "delete from t_ba_accountapplies a where a.tenantid= %s ",
    "delete from t_ba_accountupdatehis a where a.tenantid= %s ",
    "delete from t_bi_benletterofguaranteeops a where a.tenantid= %s ",
    "delete from t_fl_creditbusinesstrans a where a.tenantid= %s ",
    "delete from t_bi_benletterofguarantees a where a.tenantid= %s ",
    "delete from t_fl_creditbusinesstrans a where a.tenantid= %s ",
    "delete from t_fl_creditbusiness a where a.tenantid= %s ",
    "delete from t_fl_creditguarantees a where a.tenantid= %s ",
    "delete from t_bi_impletterofcredits a where a.tenantid= %s ",
    "delete from t_fl_credits a where a.tenantid= %s ",
    "delete from t_bi_expletterofcreditops a where a.tenantid= %s ",
    "delete from t_bi_expletterofcredits a where a.tenantid= %s ",
    "delete from t_fi_investcategories a where a.tenantid= %s ",
    "delete from t_fi_currentinvestcontract a where a.tenantid= %s ",
    "delete from t_fl_bondissuanceconsignees a where a.tenantid= %s ",
    "delete from t_fl_bondaccounts a where a.tenantid= %s ",
    "delete from t_fl_bondredeems a where a.tenantid= %s ",
    "delete from t_fl_bondinterests a where a.tenantid= %s ",
    "delete from t_fl_bondrepayplans a where a.tenantid= %s ",
    "delete from t_fl_bondinterestdetails a where a.tenantid= %s ",
    "delete from t_fl_bondinterests a where a.tenantid= %s ",
    "delete from t_fl_bondissuances a where a.tenantid= %s ",
    "delete from t_fl_bondregisterconsignees a where a.tenantid= %s ",
    "delete from t_fl_bondregisters a where a.tenantid= %s ",
    "delete from t_gl_accounts a where a.tenantid= %s ",
    "delete from t_gl_interfaceorgrels a where a.tenantid= %s ",
    "delete from t_bi_impletterofcreditops a where a.tenantid= %s ",
    "delete from t_fl_loanquotas a where a.tenantid= %s ",
    "delete from t_bi_paydraftoperations a where a.tenantid= %s ",
    "delete from t_bi_prinletterofguaranteeops a where a.tenantid= %s ",
    "delete from t_bi_prinletterofguarantees a where a.tenantid= %s ",
    "delete from t_pm_projectitems a where a.tenantid= %s ",
    "delete from t_bi_recdraftoperations a where a.tenantid= %s ",
    "delete from t_bd_departments a where a.tenantid= %s ",
    "delete from t_bd_userdataauthority a where a.tenantid= %s ",
    "delete from T_BA_ACCOUNTS a where a.tenantid= %s ",
    "delete from T_SS_ADMINISTRATION a where a.tenantid= %s ",
    "delete from T_SS_EQUITYSTRUCTURES a where a.tenantid= %s ",
    "delete from T_SS_COMPANIES a where a.tenantid= %s ",
    "delete from T_FI_BANKFINANCIALPRODAPPLYS a where a.tenantid= %s ",
    "delete from T_FI_CASHINVESTDETAILS a where a.tenantid= %s ",
    "delete from t_bu_budgetitemscopes a where a.tenantid= %s ",
    "delete from t_bu_budgetitems  a where a.tenantid= %s ",
    "delete from T_FI_CASHINVESTS a where a.tenantid= %s ",
    "delete from T_IV_TRANSACTIONS a where a.tenantid= %s ",
    "delete from T_IV_BALANCES a where a.tenantid= %s ",
    "delete from T_SE_PAYMENTAPPLYS a where a.tenantid= %s ",
    "delete from T_IV_ACCOUNTS a where a.tenantid= %s ",
    "delete from T_IV_ACCOUNTPOOLS a where a.tenantid= %s ",
    "delete from T_SE_PAYRECORDADJUSTS a where a.tenantid= %s ",
    "delete from T_BD_TASKSCHEDULERS a where a.tenantid= %s ",
    "delete from T_BD_TASKSCHEDULERS a where a.taskid in (select a.urid from T_BD_TASKS a where a.tenantid= %s )",
    "delete from T_BD_TASKS a where a.tenantid= %s ",
    "delete from T_SE_PAYRECORDS a where a.tenantid= %s ",
    "delete from TSYS_TEMPORARYDATA a where a.tenantid= %s ",
    "delete from TSYS_ORGANIZATION a where a.tenantid= %s ",
    "delete from JBPM4_EXT_FORMCLASS a where a.tenantid= %s ",
    "delete from JBPM4_EXT_VER a where a.tenantid= %s ",
    "delete from JBPM4_EXT_PROCESS_TYPE a where a.tenantid= %s ",
    "delete from JBPM4_EXT_FORMREG a where a.tenantid= %s ",
    "delete from TSYS_ROLE_RIGHT a where a.tenantid= %s ",
    "delete from TSYS_ROLE a where a.tenantid= %s ",
    "delete from TSYS_USER_LOGIN a where a.tenantid= %s ",
    "delete from TSYS_LOG a where a.tenantid= %s ",
    "delete from tsys_org_user a where a.tenantid= %s ",
    "delete from TSYS_CONTRACT a where a.tenantid= %s ",
    "delete from TSYS_POSITION a where a.tenantid= %s ",
    "delete from T_SY_DIRECTBANKS a where a.tenantid= %s ",
    "delete from biz_batch_list a where a.tenantid= %s ",
    "delete from biz_batch a where a.tenantid= %s ",
    "delete from jbpm4_deployment a where a.tenantid= %s ",
    "delete from jbpm4_variable a where a.tenantid= %s ",
    "delete from jbpm4_execution a where a.tenantid= %s ",
    "delete from jbpm4_ext_hist_task a where a.tenantid= %s ",
    "delete from jbpm4_ext_start a where a.tenantid= %s ",
    "delete from jbpm4_ext_taskdef_detail a where a.tenantid= %s ",
    "delete from jbpm4_hist_actinst a where a.tenantid= %s ",
    "delete from jbpm4_hist_procinst a where a.tenantid= %s ",
    "delete from jbpm4_hist_task a where a.tenantid= %s ",
    "delete from jbpm4_hist_var a where a.tenantid= %s ",
    "delete from jbpm4_participation a where a.tenantid= %s ",
    "delete from jbpm4_task a where a.tenantid= %s ",
    "delete from jbpm4_ext_template_data a where a.tenantid= %s ",
    "delete from tsys_user_message a where a.tenantid= %s ",
    "delete from T_SS_COMPANIES a where a.tenantid= %s ",
    "delete from TSYS_ORGANIZATION a where a.tenantid= %s ",
    "delete from TSVCVIEWCONFIGCUSTOM a where a.tenantid= %s ",
    "delete from jbpm4_ext_delegate a where a.tenantid=%s ",
    "delete from TSYS_TENANT a where a.tenantid= %s "]
